// <auto-generated />
using System;
using MeatSpeak.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeatSpeak.Server.Data.Migrations
{
    [DbContext(typeof(MeatSpeakDbContext))]
    partial class MeatSpeakDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.AuditLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("Timestamp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Actor");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_log", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ChannelEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Modes")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TopicSetAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopicSetBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int?>("UserLimit")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("channels", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ChannelOverrideEntity", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<ulong>("Allow")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Deny")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoleId", "ChannelName");

                    b.ToTable("channel_overrides", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ChatLogEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRedacted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("MsgId")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RedactedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RedactedBy")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("SentAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Target")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName");

                    b.HasIndex("MsgId")
                        .IsUnique();

                    b.HasIndex("Sender");

                    b.HasIndex("SentAt");

                    b.ToTable("chat_logs", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ReactionEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MsgId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reaction")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MsgId");

                    b.HasIndex("MsgId", "Sender", "Reaction")
                        .IsUnique();

                    b.ToTable("reactions", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DefaultChannelPermissions")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ServerPermissions")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ServerBanEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ExpiresAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mask")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("SetAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mask");

                    b.ToTable("server_bans", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.TopicHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("SetAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SetBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelName");

                    b.ToTable("topic_history", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.UserHistoryEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Account")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DisconnectedAt")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hostname")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("QuitReason")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account");

                    b.HasIndex("Nickname");

                    b.ToTable("user_history", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.UserRoleEntity", b =>
                {
                    b.Property<string>("Account")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Account", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.ChannelOverrideEntity", b =>
                {
                    b.HasOne("MeatSpeak.Server.Data.Entities.RoleEntity", "Role")
                        .WithMany("ChannelOverrides")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.UserRoleEntity", b =>
                {
                    b.HasOne("MeatSpeak.Server.Data.Entities.RoleEntity", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MeatSpeak.Server.Data.Entities.RoleEntity", b =>
                {
                    b.Navigation("ChannelOverrides");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
